### ISSUE TITLE
What value does this repo add over the hook provided by bandit itself?

### ISSUE THREAD

**Issue by Wouterkoorn** [Lucas-C/pre-commit-hooks-bandit#19]
Bandit also provides a hook: [https://github.com/PyCQA/bandit/blob/main/.pre-commit-hooks.yaml](https://github.com/PyCQA/bandit/blob/main/.pre-commit-hooks.yaml).
Is there any reason to use the hook in this library?

**Comment by Lucas-C** [comment]
I simply did not know that an official hook existed!
This repo exists since 2016, whereas the official bandit hook was created in 2018: https://github.com/PyCQA/bandit/commits/main/.pre-commit-hooks.yaml

I'm going to archive this repo and add a message refering to the official one.
Thank you for asking the question 😊
